### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by devve2kccc** [sleeyax/stremio-streaming-server#10]
Im getting "Failed to fetch" error when i try so start a movie with torrentio plugin, what can be?

**Comment by kvn1351** [comment]
Same

**Comment by sleeyax** [comment]
More details are needed:

- Which movie?
- Which Stremio version (4, 5, web or client)?

**Comment by Nicohidalgo** [comment]
I get the same error when i try to watch any movie with any addon

![image](https://user-images.githubusercontent.com/45693668/177079836-f9cf037c-61ef-4751-aedd-600bddc8c01f.png)

**Comment by Nicohidalgo** [comment]
I think this is the problem but I don't know how to fix it
![image](https://user-images.githubusercontent.com/45693668/177080014-a71c8c3d-ea29-4596-a96f-5c8ffddbd572.png)
![image](https://user-images.githubusercontent.com/45693668/177080147-44c0b35d-ddc4-4e2c-86c3-1580a07791a8.png)

**Comment by sleeyax** [comment]
@Nicohidalgo it says streaming server not available. Check if the streaming server url is correct and disable any firewall or AV. A quick smoke test id to ping the host.

**Comment by kvn1351** [comment]
I have the same issue, Stremio can't connect to the server. When I enter \<serverIP\>:11470 in the browser it takes me straight to Stremio with the correct settings. However, the server "is not available".

```yaml
version: "2.1"
services:
  stremio-server:
    image: sleeyax/stremio-streaming-server
    container_name: stremio-streaming-server
    environment:
      - TZ=Europe/Berlin
    volumes:
      - redacted
    ports:
      - 11470:11470
    restart: unless-stopped
```

I have about 15 other dockers that work fine from this same server. So it's not a network issue. Not the environment at least.
