### ISSUE TITLE
stremio-server.json missing

### ISSUE THREAD

**Issue by Makanz** [sleeyax/stremio-streaming-server#13]
Found that the settings file server-settings.json is missing when starting up the image.

Solved it by creating a json file manually. 
Is it possible to add a command in start.sh to create a settings file if it´s missing?

**Comment by sleeyax** [comment]
The settings file gets created on startup at the path `/root/.stremio-server/server-settings.json`. You can find it on your host machine as well, depending on where you mounted the volume. For example, if you bind the volume with  `-v /var/tmp/stremio:/root/.stremio-server`, then you should find the settings file at `/var/tmp/stremio/server-settings.json` on your host after running the container for the first time.

**Comment by Makanz** [comment]
I did that but the file was not created.

Created a docker-compose file:

```
version: "3"

services:
  stremio-server:
    image: sleeyax/stremio-streaming-server
    container_name: stremio-server
    restart: unless-stopped
    environment:
      - FIX_CORS=1
    ports:
      - 11470:11470
    volumes:
      - /mnt/MD0-DATA/docker/stremio-server:/root/.stremio-server
```
![error_message](https://user-images.githubusercontent.com/4232943/179426202-dd97942f-03b4-401a-bef9-0c8bfb0b2d47.png)
