### ISSUE TITLE
adding surfshark VPN?

### ISSUE THREAD

**Issue by Waldorf3** [sleeyax/stremio-streaming-server#19]
I tried adding a surfshark container in front of the server, using a docker-compose.yml modified from [docker-surfshark](https://github.com/ilteoood/docker-surfshark):

```
services: 
    surfshark-stremio:
        image: ilteoood/docker-surfshark
        container_name: surfshark-stremio
        environment: 
            - SURFSHARK_USER=_redacted_
            - SURFSHARK_PASSWORD=_redacted_
            - SURFSHARK_COUNTRY=_redacted_
            - SURFSHARK_CITY=_redacted_
            - CONNECTION_TYPE=udp
            - LAN_NETWORK=192.168.10.0/24
        cap_add: 
            - NET_ADMIN
        devices:
            - /dev/net/tun
        ports:
            - 11470:11470
        restart: unless-stopped
        dns:
            - 1.1.1.1
    stremio:
        image: sleeyax/stremio-streaming-server:latest
        container_name: stremio
        environment:
            - FIX_UNSUPPORTED_MEDIA=1
        volumes:
            - stremio:/root/.stremio-server
        network_mode: service:surfshark-stremio
        restart: unless-stopped
volumes:
    stremio:
```

I can connect to stremio through a browser on the local network, but it throws this error:

![image](https://user-images.githubusercontent.com/104714194/210563637-b0c1f216-df11-4fc8-a08e-fd2d8fbd6ddc.png)

The source transmission-surfshark docker-compose works fine. (I removed the service_test as it serves no purpose anyway.)

I'm open for other ways to accomplish this, just based it on an example I know works.
